### PR TITLE
NodeBB v2.x compatibility

### PR DESCRIPTION
**Pull request by julianlam**

### CODE REVIEW

**Comment by julianlam** [comment]
Hi @NicolasSiver — this PR was not tested against an actual instance with awards set up... we had a report that the plugin was throwing a `maxRewardsPerPost` error on topic entry, but I cannot reproduce it currently (although I have no rewards set up).

Otherwise, this PR fixes all errors thrown during NodeBB startup.

**Comment by julianlam** [comment]
`public/js/acp.js` might need to be moved to `modules` in `plugin.json`, but when I went into the file, I was greeted with a wall of minified javascript :laughing:

**Comment by julianlam** [comment]
_bump_ :smiley_cat:

**Comment by NicolasSiver** [comment]
Hello @julianlam did you do basic sanity testing with the changes? I just pulled your PR and it plugin does not function at all with 2.2.x.

**Comment by NicolasSiver** [comment]
I did a small change to Modules, but the Upload does not work. I currently do not have time to dig into the architecture changes in NodeBB v2. If you have the desire and time to prepare fully working PR, I will be happy to groom it and merge. The current state - it's a bit dysfunctional.

**Comment by julianlam** [comment]
No, no testing with an actual database with values set, just startup errors. I can take a closer look.

**Comment by NicolasSiver** [comment]
@julianlam I think there is an issue with this line - https://github.com/NicolasSiver/nodebb-plugin-ns-awards/blob/8d3c8364b0da1011bef8a937dfac97b9f2cb7ba9/plugin/uploads.js#L58
Was there a change in NodeBB v2 that impacts `hasListeners` function in Plugins module?

**Comment by NicolasSiver** [comment]
It will be in some way reckless to bring these changes to master. I'm going to bring them to an optimistic branch, will see how it will go to make it work ;)

**Pull request merged**
